server:
  port: 8080
  servlet:
    context-path: /app

spring:
  multipart:
    max-file-size: 100MB
    max-request-size: 1000MB
  mail:
    username: sending060425@gmail.com
    password: qrwb kauf juku gyqt
    properties:
      mail.smtp.auth: true
      mail.smtp.starttls.enable: true
    host: smtp.gmail.com
    port: 587
  datasource:
    url: "jdbc:mysql://${MYSQL_HOST:localhost}:${MYSQL_PORT:3306}/salus"
    username: ${MYSQL_USER:root}
    password: ${MYSQL_PASSWORD:666666}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  data:
    redis:
      host: localhost
      port: 6380
jwt:
  signerKey: "b4ISo6+PT1fY8eppQ564SXabONN945cjuPYa0mTOmPrThHVxEnH7+xxE5RFJCqtk"
upload:
  dir: upload/img/